# Render.com deployment configuration for Zone Meet
# This file defines infrastructure as code for automatic deployment

services:
  # Main web service for Zone Meet application
  - type: web
    name: appointmentsCalendar
    runtime: node
    region: ohio
    plan: starter
    
    # Build configuration
    buildCommand: cd appointments_calendar && npm ci && npx prisma generate && npm run build
    startCommand: cd appointments_calendar && npm start
    
    # Environment variables
    envVars:
      # Core application settings
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      
      # WAF (Web Application Firewall) settings
      - key: WAF_ENABLED
        value: true
      - key: WAF_RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: WAF_RATE_LIMIT_WINDOW
        value: 60000
      - key: WAF_BLOCK_SUSPICIOUS_PATTERNS
        value: false
      
      # Security headers and monitoring
      - key: SECURITY_HEADERS_ENABLED
        value: true
      
      # Next.js build optimization for Render
      - key: NEXT_BUILD_CACHE
        value: "false"
      
      # Note: The following sensitive values must be set in Render dashboard:
      # - DATABASE_URL (Supabase PostgreSQL connection string)
      # - DIRECT_URL (Supabase direct connection for migrations)
      # - JWT_SECRET (32+ character random string for JWT tokens)
      # - NEXTAUTH_SECRET (32+ character random string for NextAuth)
      # - MAILEROO_API_KEY (Maileroo SMTP API key)
      # - MAILEROO_FROM_EMAIL (Verified sender email address)
      # - GOOGLE_CLIENT_ID (Google OAuth app client ID)
      # - GOOGLE_CLIENT_SECRET (Google OAuth app client secret)
      # - MICROSOFT_CLIENT_ID (Microsoft Graph app client ID)
      # - MICROSOFT_CLIENT_SECRET (Microsoft Graph app client secret)
      # - OUTLOOK_CLIENT_ID (Outlook calendar app client ID)
      # - OUTLOOK_CLIENT_SECRET (Outlook calendar app client secret)
      # - TEAMS_CLIENT_ID (Microsoft Teams app client ID)
      # - TEAMS_CLIENT_SECRET (Microsoft Teams app client secret)
      # - CRON_SECRET (Secret for scheduled maintenance endpoints)
    
    # Health check configuration
    healthCheckPath: /api/health
    
    # Automatic deployment
    autoDeploy: true
    
    # Custom domains (configure after deployment in Render dashboard)
    domains:
      # - www.zone-meet.com
      # - zone-meet.com
    
    # Scaling configuration
    numInstances: 1
    
# Background jobs service (if needed for email, calendar sync)
# Uncomment if you have background processing needs
#  - type: worker
#    name: zone-meet-worker
#    runtime: node
#    region: ohio
#    buildCommand: cd appointments_calendar && npm ci
#    startCommand: npm run worker
#    envVarsFrom:
#      - service: appointmentsCalendar
#    autoDeploy: true

# Static site for documentation (optional)
# Uncomment if you want to host docs separately
#  - type: static
#    name: zone-meet-docs
#    buildCommand: npm run build:docs
#    staticPublishPath: ./docs/dist

# Environment variable groups (shared across services)
envVarGroups:
  - name: shared-config
    envVars:
      - key: LOG_LEVEL
        value: info
      - key: APP_NAME
        value: "Zone Meet"
      - key: APP_VERSION
        value: "1.0.0"