# Render.com deployment configuration for Zone Meet
# This file defines infrastructure as code for automatic deployment

services:
  # Main web service for Zone Meet application
  - type: web
    name: appointmentsCalendar
    runtime: node
    region: ohio
    plan: starter
    
    # Build configuration
    buildCommand: cd appointments_calendar && npm ci && npx prisma generate && npm run build
    startCommand: cd appointments_calendar && npm start
    
    # Environment variables
    envVars:
      # Core application settings
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      
      # WAF (Web Application Firewall) settings
      - key: WAF_ENABLED
        value: true
      - key: WAF_RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: WAF_RATE_LIMIT_WINDOW
        value: 60000
      - key: WAF_BLOCK_SUSPICIOUS_PATTERNS
        value: true
      
      # Security headers and monitoring
      - key: SECURITY_HEADERS_ENABLED
        value: true
      
      # Note: Sensitive values like DATABASE_URL, JWT_SECRET, API keys
      # should be set in Render dashboard or via environment sync
    
    # Health check configuration
    healthCheckPath: /api/health
    
    # Automatic deployment
    autoDeploy: true
    
    # Custom domains (configure after deployment in Render dashboard)
    domains:
      # - www.zone-meet.com
      # - zone-meet.com
    
    # Scaling configuration
    numInstances: 1
    
# Optional: Redis service for caching/sessions
# Uncomment if you need Redis for session storage or caching
#  - type: redis
#    name: zone-meet-redis
#    plan: starter
#    region: ohio

# Background jobs service (if needed for email, calendar sync)
# Uncomment if you have background processing needs
#  - type: worker
#    name: zone-meet-worker
#    runtime: node
#    region: ohio
#    buildCommand: cd appointments_calendar && npm ci
#    startCommand: npm run worker
#    envVarsFrom:
#      - service: appointmentsCalendar
#    autoDeploy: true

# Static site for documentation (optional)
# Uncomment if you want to host docs separately
#  - type: static
#    name: zone-meet-docs
#    buildCommand: npm run build:docs
#    staticPublishPath: ./docs/dist

# Environment variable groups (shared across services)
envVarGroups:
  - name: shared-config
    envVars:
      - key: LOG_LEVEL
        value: info
      - key: APP_NAME
        value: "Zone Meet"
      - key: APP_VERSION
        value: "1.0.0"